version: "3"
services:
  bot:
    build:
      context: .
      dockerfile: docker/Dockerfile-prod
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
