FROM node:12-alpine

# Create the directory!
RUN mkdir -p /usr/src/bot
WORKDIR /usr/src/bot

# Copy and Install our bot
COPY package*.json /usr/src/bot/
RUN npm install --prod
COPY . /usr/src/bot
USER node
# Start me!
CMD ["npm", "run", "serve"]
